### ISSUE TITLE
The same user is in a group multiple times which creates weird behaviour??

### ISSUE THREAD

**Issue by HannahSonntag** [source-data/sdash#209] opened 2021-05-03 15:53 UTC
I dont know how this came to happen. 
![Screenshot 2021-05-03 at 17 49 19](https://user-images.githubusercontent.com/56673511/116899775-4292e000-ac38-11eb-9fd0-385ccd2e48c8.png)

And I actually cannot reproduce. I cannot add the same user twice to a group? Maybe a bug when opting in?

**Comment by eidens** [comment] 2021-12-10 16:19
I can't reproduce this and haven't seen anything like it in a long time. Closing.

**Closed by eidens** 2021-12-10 16:19 UTC
Labels: bug
